const os_mcq = {
    1: {
      question: "Which scheduling algorithm is most suitable for a time-sharing operating system?",
      options: {
        1: "First Come First Serve (FCFS)",
        2: "Shortest Job Next (SJN)",
        3: "Round Robin (RR)",
        4: "Priority Scheduling",
      },
      correctAnswer: 3,
      explanation:
        "Round Robin scheduling is designed for time-sharing systems as it allocates CPU time slices equally among processes, ensuring responsiveness for all tasks.",
    },
    2: {
      question: "What is the main advantage of using multithreading?",
      options: {
        1: "Improves single-thread performance",
        2: "Enables parallel execution of processes",
        3: "Reduces context-switching overhead",
        4: "Allows concurrent execution within a process",
      },
      correctAnswer: 4,
      explanation:
        "Multithreading allows multiple threads within the same process to execute concurrently, improving responsiveness and resource utilization.",
    },
    3: {
      question: "In a deadlock situation, which condition does not belong to the four necessary conditions?",
      options: {
        1: "Mutual Exclusion",
        2: "Circular Wait",
        3: "Preemption",
        4: "Hold and Wait",
      },
      correctAnswer: 3,
      explanation:
        "Preemption is not one of the four necessary conditions for deadlock. The four conditions are mutual exclusion, hold and wait, no preemption, and circular wait.",
    },
    4: {
      question: "Which of the following is used to implement process synchronization?",
      options: {
        1: "Semaphore",
        2: "Round Robin Scheduling",
        3: "Paging",
        4: "Thrashing",
      },
      correctAnswer: 1,
      explanation:
        "Semaphores are synchronization primitives used to manage access to shared resources and prevent race conditions.",
    },
    5: {
      question: "What does the term 'context switch' refer to?",
      options: {
        1: "Switching between different operating systems",
        2: "Switching between user and kernel modes",
        3: "Saving the state of a process for resumption later",
        4: "Changing CPU scheduling algorithms",
      },
      correctAnswer: 3,
      explanation:
        "A context switch occurs when the CPU saves the state of the current process and loads the state of another process, enabling multitasking.",
    },
    6: {
      question: "What is the main purpose of virtual memory?",
      options: {
        1: "To improve the speed of the CPU",
        2: "To provide more memory than physically available",
        3: "To ensure thread synchronization",
        4: "To improve disk performance",
      },
      correctAnswer: 2,
      explanation:
        "Virtual memory extends the available memory by using disk space as an extension of RAM, allowing processes to use more memory than physically available.",
    },
    7: {
      question: "Which of the following is a characteristic of a real-time operating system?",
      options: {
        1: "Batch processing",
        2: "Deterministic response time",
        3: "Multitasking",
        4: "Memory paging",
      },
      correctAnswer: 2,
      explanation:
        "Real-time operating systems guarantee deterministic response times, ensuring critical tasks are executed within strict deadlines.",
    },
    8: {
      question: "What is the role of the page table in a paging system?",
      options: {
        1: "Stores the processes currently in memory",
        2: "Maps logical addresses to physical addresses",
        3: "Keeps track of free memory blocks",
        4: "Manages file system operations",
      },
      correctAnswer: 2,
      explanation:
        "The page table maps logical addresses generated by the CPU to their corresponding physical addresses in memory.",
    },
    9: {
      question: "What happens when a process tries to access memory that it does not have permission for?",
      options: {
        1: "Deadlock occurs",
        2: "Segmentation fault",
        3: "Thrashing",
        4: "Context switch",
      },
      correctAnswer: 2,
      explanation:
        "A segmentation fault occurs when a process tries to access memory outside its allocated region, violating memory access rules.",
    },
    10: {
      question: "Which of the following disk scheduling algorithms minimizes seek time the most?",
      options: {
        1: "First Come First Serve (FCFS)",
        2: "Shortest Seek Time First (SSTF)",
        3: "SCAN",
        4: "C-SCAN",
      },
      correctAnswer: 2,
      explanation:
        "Shortest Seek Time First (SSTF) minimizes seek time by servicing requests closest to the current disk head position, reducing head movement.",
    },
  };

  export default os_mcq;